name: rj_blocx
description: RJ BlocX - Rahul Verma's powerful Flutter CLI tool for generating projects with BloC architecture, clean code structure, and best practices.
version: 2.0.0
# Remove the deprecated 'author' field
homepage: https://github.com/RahulDev-flutter/blocx_cli
repository: https://github.com/RahulDev-flutter/blocx_cli
issue_tracker: https://github.com/RahulDev-flutter/blocx_cli/issues
documentation: https://github.com/RahulDev-flutter/blocx_cli#readme

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.2
  path: ^1.8.3
  prompts: ^2.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

# Fixed executables section
executables:
  rj_blocx: blocx  # This maps 'rj_blocx' command to 'bin/blocx.dart'
  # Optional: Also allow 'blocx' as a command
  blocx: blocx     # This maps 'blocx' command to 'bin/blocx.dart'