name: blocx
description: A CLI tool to generate BLoC + Clean Architecture boilerplate.
version: 1.0.0
repository: https://github.com/RahulDev-flutter/blocx_cli

environment:
  sdk: ^3.9.0

executables:
  blocx: blocx

dependencies:
  path: ^1.9.1
  args: ^2.7.0
  io: ^1.0.5

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
