name: RJ BlocX CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test RJ BlocX CLI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Get dependencies
        run: dart pub get

      # Option 1: Auto-format and commit back (for push events only)
      - name: Format code
        if: github.event_name == 'push'
        run: dart format .

      - name: Commit formatted code
        if: github.event_name == 'push'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff --staged --quiet || git commit -m "Auto-format code with dart format"
          git push

      # Option 2: Just verify formatting for PRs
      - name: Verify formatting
        if: github.event_name == 'pull_request'
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: dart analyze --fatal-infos

      - name: Run tests
        run: dart test

  integration-test:
    name: Integration Test
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'  # Updated to a more recent stable version

      - name: Get dependencies
        run: dart pub get

      - name: Test RJ BlocX CLI commands
        run: |
          # Activate local version
          dart pub global activate --source path .
          
          # Test help command
          rj_blocx --help
          
          # Test version command
          rj_blocx --version
          
          # Test create command validation
          mkdir -p /tmp/test_projects
          cd /tmp/test_projects
          echo "Testing RJ BlocX project creation..."

  build:
    name: Build RJ BlocX Executable
    runs-on: ubuntu-latest
    needs: [test, integration-test]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Get dependencies
        run: dart pub get

      - name: Build executable
        run: dart compile exe bin/rj_blocx.dart -o build/rj_blocx

      - name: Test executable
        run: |
          ./build/rj_blocx --version
          ./build/rj_blocx --help

      - name: Upload build artifact
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: rj_blocx-executable
          path: build/rj_blocx

  release:
    name: Create RJ BlocX Release
    runs-on: ubuntu-latest
    needs: [test, integration-test, build]
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Get dependencies
        run: dart pub get

      - name: Build executables
        run: |
          mkdir -p build
          dart compile exe bin/rj_blocx.dart -o build/rj_blocx-linux

      - name: Create Release
        uses: softprops/action-gh-release@v1  # Updated to more maintained action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: RJ BlocX CLI ${{ github.ref_name }}
          body: |
            ## 🚀 RJ BlocX CLI - Created by Rahul Verma
            
            ### What's Changed
            
            See [CHANGELOG.md](CHANGELOG.md) for detailed changes.
            
            ### Installation
            
            ```bash
            dart pub global activate --source git https://github.com/RahulDev-flutter/blocx_cli.git
            ```
            
            ### Verification
            
            ```bash
            rj_blocx --version
            ```
            
            ### Quick Start
            
            ```bash
            rj_blocx create my_awesome_app
            ```
            
            ---
            
            **Made with ❤️ by Rahul Verma**
          files: build/rj_blocx-linux
          draft: false
          prerelease: false